---
- name: Install sudo (RedHat-like)
  ansible.builtin.package:
    name: sudo
    state: present

- name: Create sudoers.d directory
  ansible.builtin.file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0750
    state: directory

- name: Set includedir in sudoers
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: Create sudoers
  ansible.builtin.template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/{{ sudoers_filename }}"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
  when: not sudoers_remove

- name: Remove sudoers
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ sudoers_filename }}"
    state: absent
  when: sudoers_remove
